apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: dind-agent
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: tcp://host.docker.internal:2375
